/**
 * Build grocery_list (JSON) and prep_guide (text) from PlannedMeals + FoodItems
 * (or MealPlanItems) and persist on MealPlans. Used by MealPlanList and MealPlanDetail.
 *
 * Food categorization: contains-match keyword tables (longest phrases first). Pantry is checked
 * before dairy/meat & fish/produce so oils, condiments, and plant milks map to Pantry.
 */

/** Internal prep buckets; `grain` historically = pantry / grains / dry goods. */
type FoodKind = 'grain' | 'dairy' | 'meatFish' | 'produce' | 'other';

function sortKeywordsLongestFirst(keywords: readonly string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const k of keywords) {
    const t = k.toLowerCase().trim();
    if (t && !seen.has(t)) {
      seen.add(t);
      out.push(t);
    }
  }
  return out.sort((a, b) => b.length - a.length);
}

/**
 * Multi-word phrases: substring match. Single words: delimiter-aware match so we don't hit
 * substrings like pea→pear, tuna→fortuna, oil→boil, beef→beefsteak.
 */
function matchesKeyword(haystackLower: string, keyword: string): boolean {
  const kw = keyword.toLowerCase();
  if (kw.includes(' ')) {
    return haystackLower.includes(kw);
  }
  const escaped = kw.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`(^|[^a-z0-9])${escaped}([^a-z0-9]|$)`, 'i');
  return re.test(haystackLower);
}

/**
 * Pantry: oils, vinegars, condiments, sauces, spices, nuts, seeds, nut butters, canned/dried shelf
 * staples, grains, pasta, bread, tortillas, crackers, flour, sugar, sweeteners, coffee, tea, baking.
 */
const PANTRY_KEYWORDS = sortKeywordsLongestFirst([
  'apple cider vinegar',
  'white wine vinegar',
  'red wine vinegar',
  'rice vinegar',
  'balsamic vinegar',
  'distilled vinegar',
  'worcestershire sauce',
  'worcestershire',
  'vegetable oil',
  'sunflower oil',
  'grapeseed oil',
  'coconut oil',
  'sesame oil',
  'avocado oil',
  'canola oil',
  'olive oil',
  'peanut oil',
  'cooking spray',
  'nonstick spray',
  'almond butter',
  'cashew butter',
  'sunflower butter',
  'walnut butter',
  'peanut butter',
  'nut butter',
  'coconut milk',
  'almond milk',
  'oat milk',
  'soy milk',
  'cashew milk',
  'rice milk',
  'hemp milk',
  'macadamia milk',
  'coconut cream',
  'tomato paste',
  'tomato sauce',
  'pasta sauce',
  'marinara sauce',
  'alfredo sauce',
  'enchilada sauce',
  'bbq sauce',
  'barbecue sauce',
  'teriyaki sauce',
  'oyster sauce',
  'hoisin sauce',
  'fish sauce',
  'soy sauce',
  'tamari sauce',
  'hot sauce',
  'sriracha',
  'chili sauce',
  'buffalo sauce',
  'salad dressing',
  'italian dressing',
  'ranch dressing',
  'caesar dressing',
  'mayonnaise',
  'mirin',
  'rice wine',
  'dijon mustard',
  'yellow mustard',
  'whole grain mustard',
  'stone ground mustard',
  'relish',
  'pickle relish',
  'ketchup',
  'mustard',
  'mayo',
  'vinegar',
  'salsa',
  'guacamole',
  'hummus',
  'tahini',
  'pesto',
  'harissa',
  'gochujang',
  'miso paste',
  'miso',
  'curry paste',
  'curry powder',
  'chili powder',
  'cayenne pepper',
  'garlic powder',
  'onion powder',
  'smoked paprika',
  'chili flakes',
  'red pepper flakes',
  'italian seasoning',
  'poultry seasoning',
  'pumpkin pie spice',
  'garam masala',
  'five spice',
  'bay leaves',
  'bay leaf',
  'vanilla extract',
  'almond extract',
  'baking powder',
  'baking soda',
  'corn starch',
  'cornstarch',
  'arrowroot',
  'xanthan gum',
  'active dry yeast',
  'instant yeast',
  'nutritional yeast',
  'cocoa powder',
  'chocolate chips',
  'chocolate chunk',
  'semi-sweet chocolate',
  'dark chocolate',
  'maple syrup',
  'agave nectar',
  'simple syrup',
  'simple sugar',
  'brown sugar',
  'powdered sugar',
  'confectioners sugar',
  'coconut sugar',
  'date syrup',
  'molasses',
  'corn syrup',
  'stevia',
  'sweetener',
  'granola',
  'cereal',
  'instant oatmeal',
  'rolled oats',
  'steel cut oats',
  'quick oats',
  'oat bran',
  'wheat bran',
  'bread crumbs',
  'panko',
  'cracker',
  'crackers',
  'pretzel',
  'tortilla chip',
  'potato chip',
  'corn chip',
  'tortilla',
  'tortillas',
  'corn tortilla',
  'flour tortilla',
  'wrap',
  'wraps',
  'pita',
  'pita bread',
  'naan',
  'flatbread',
  'bagel',
  'bagels',
  'english muffin',
  'croissant',
  'brioche',
  'sourdough',
  'bread',
  'bun',
  'buns',
  'roll',
  'dinner roll',
  'hoagie roll',
  'slider bun',
  'rice noodle',
  'egg noodle',
  'ramen noodle',
  'udon',
  'soba',
  'vermicelli',
  'spaghetti',
  'penne',
  'fusilli',
  'macaroni',
  'fettuccine',
  'linguine',
  'orzo',
  'lasagna noodle',
  'pasta',
  'noodle',
  'noodles',
  'couscous',
  'polenta',
  'grits',
  'cornmeal',
  'masa harina',
  'tortilla flour',
  'all-purpose flour',
  'bread flour',
  'cake flour',
  'whole wheat flour',
  'almond flour',
  'coconut flour',
  'rice flour',
  'tapioca flour',
  'chickpea flour',
  'flour',
  'rice',
  'brown rice',
  'white rice',
  'jasmine rice',
  'basmati rice',
  'wild rice',
  'arborio rice',
  'sushi rice',
  'quinoa',
  'farro',
  'barley',
  'bulgur',
  'freekeh',
  'millet',
  'buckwheat',
  'amaranth',
  'sorghum',
  'chia seed',
  'chia seeds',
  'flax seed',
  'flaxseed',
  'hemp seed',
  'hemp hearts',
  'pumpkin seed',
  'pumpkin seeds',
  'sunflower seed',
  'sunflower seeds',
  'sesame seed',
  'sesame seeds',
  'poppy seed',
  'mixed nuts',
  'trail mix',
  'walnut',
  'walnuts',
  'pecan',
  'pecans',
  'almond',
  'almonds',
  'cashew',
  'cashews',
  'pistachio',
  'pistachios',
  'hazelnut',
  'hazelnuts',
  'macadamia',
  'brazil nut',
  'pine nut',
  'pine nuts',
  'peanut',
  'peanuts',
  'raisin',
  'raisins',
  'dried cranberry',
  'dried apricot',
  'dried mango',
  'dried fig',
  'prune',
  'prunes',
  'dried dates',
  'medjool dates',
  'deglet noor',
  'beef jerky',
  'turkey jerky',
  'protein bar',
  'casein protein',
  'whey protein',
  'hemp protein',
  'pea protein',
  'collagen powder',
  'protein powder',
  'granola bar',
  'energy bar',
  'canned tomato',
  'canned corn',
  'canned coconut',
  'canned pumpkin',
  'canned soup',
  'broth',
  'stock',
  'chicken broth',
  'beef broth',
  'vegetable broth',
  'bouillon',
  'bone broth',
  'coconut water',
  'sparkling water',
  'club soda',
  'tonic water',
  'coffee',
  'espresso',
  'instant coffee',
  'cold brew',
  'herbal tea',
  'green tea',
  'black tea',
  'chai tea',
  'tea bag',
  'chai',
  'matcha',
  'rooibos',
  'paprika',
  'cumin',
  'coriander',
  'turmeric',
  'cinnamon',
  'nutmeg',
  'cloves',
  'allspice',
  'cardamom',
  'fennel seed',
  'caraway',
  'dill seed',
  'mustard seed',
  'celery seed',
  'star anise',
  'saffron',
  'herbes de provence',
  'everything bagel seasoning',
  'seasoning blend',
  'seasoning mix',
  'taco seasoning',
  'ranch seasoning',
  'italian herbs',
  'dried oregano',
  'dried basil',
  'dried thyme',
  'dried rosemary',
  'dried parsley',
  'dried dill',
  'dried mint',
  'garlic salt',
  'onion salt',
  'celery salt',
  'seasoned salt',
  'kosher salt',
  'sea salt',
  'table salt',
  'black pepper',
  'white pepper',
  'pink salt',
  'msg',
  'honey',
  'syrup',
  'sugar',
  'spice',
  'spices',
  'jam',
  'jelly',
  'preserves',
  'marmalade',
  'apple butter',
  'coconut flakes',
  'shredded coconut',
  'breadcrumbs',
]);

/** Cow / traditional dairy (plant milks hit PANTRY first). */
const DAIRY_KEYWORDS = sortKeywordsLongestFirst([
  'cottage cheese',
  'cream cheese',
  'sour cream',
  'heavy cream',
  'whipping cream',
  'double cream',
  'clotted cream',
  'half and half',
  'half-and-half',
  'coffee creamer',
  'whipped cream',
  'greek yogurt',
  'greek yoghurt',
  'skim milk',
  'whole milk',
  '2% milk',
  '1% milk',
  'buttermilk',
  'chocolate milk',
  'goat milk',
  'sheep milk',
  'raw milk',
  'lactose free milk',
  'mozzarella',
  'parmesan',
  'pecorino',
  'romano',
  'cheddar',
  'swiss cheese',
  'provolone',
  'gouda',
  'brie',
  'camembert',
  'blue cheese',
  'gorgonzola',
  'feta cheese',
  'goat cheese',
  'ricotta',
  'mascarpone',
  'burrata',
  'halloumi',
  'paneer',
  'queso fresco',
  'american cheese',
  'string cheese',
  'cheese slice',
  'shredded cheese',
  'grated cheese',
  'yogurt',
  'yoghurt',
  'kefir',
  'drinkable yogurt',
  'frozen yogurt',
  'ice cream',
  'gelato',
  'sorbet',
  'butter',
  'ghee',
  'clarified butter',
  'margarine',
  'milk',
  'cream',
  'cheese',
]);

const PROTEIN_KEYWORDS = sortKeywordsLongestFirst([
  'boneless skinless chicken',
  'chicken breast',
  'chicken thigh',
  'chicken wing',
  'chicken drumstick',
  'chicken tender',
  'ground chicken',
  'rotisserie chicken',
  'turkey breast',
  'ground turkey',
  'turkey bacon',
  'turkey sausage',
  'duck breast',
  'ground beef',
  'beef steak',
  'ribeye',
  'sirloin',
  'filet mignon',
  'flank steak',
  'skirt steak',
  'brisket',
  'beef roast',
  'stew beef',
  'corned beef',
  'pastrami',
  'roast beef',
  'ground pork',
  'pork chop',
  'pork tenderloin',
  'pork shoulder',
  'pulled pork',
  'pork belly',
  'bacon',
  'pancetta',
  'prosciutto',
  'ham',
  'canadian bacon',
  'sausage',
  'chorizo',
  'andouille',
  'kielbasa',
  'bratwurst',
  'italian sausage',
  'breakfast sausage',
  'hot dog',
  'frankfurter',
  'salami',
  'pepperoni',
  'mortadella',
  'capicola',
  'deli meat',
  'lunch meat',
  'cold cuts',
  'lamb chop',
  'lamb shank',
  'ground lamb',
  'veal cutlet',
  'rabbit',
  'venison',
  'bison',
  'elk',
  'salmon fillet',
  'smoked salmon',
  'lox',
  'tuna steak',
  'canned tuna',
  'tuna pouch',
  'cod fillet',
  'halibut',
  'mahi mahi',
  'snapper',
  'grouper',
  'sea bass',
  'trout',
  'sardine',
  'anchovy',
  'mackerel',
  'herring',
  'fish fillet',
  'fish cake',
  'imitation crab',
  'surimi',
  'shrimp',
  'prawn',
  'scallop',
  'mussel',
  'clam',
  'oyster',
  'lobster',
  'crab meat',
  'crab leg',
  'calamari',
  'squid',
  'octopus',
  'seafood',
  'egg white',
  'egg yolk',
  'egg substitute',
  'liquid eggs',
  'hard boiled egg',
  'tofu',
  'silken tofu',
  'firm tofu',
  'tempeh',
  'seitan',
  'textured vegetable protein',
  'tvp',
  'edamame',
  'black bean',
  'black beans',
  'kidney bean',
  'kidney beans',
  'pinto bean',
  'pinto beans',
  'navy bean',
  'navy beans',
  'cannellini bean',
  'cannellini beans',
  'great northern bean',
  'lima bean',
  'lima beans',
  'fava bean',
  'fava beans',
  'garbanzo',
  'chickpea',
  'chickpeas',
  'refried beans',
  'baked beans',
  'lentil',
  'lentils',
  'split pea',
  'split peas',
  'black-eyed pea',
  'field pea',
  'egg',
  'eggs',
  'chicken',
  'turkey',
  'beef',
  'pork',
  'lamb',
  'veal',
  'fish',
  'tuna',
  'salmon',
  'cod',
  'tilapia',
]);

const PRODUCE_KEYWORDS = sortKeywordsLongestFirst([
  'sweet potato',
  'sweet potatoes',
  'fingerling potato',
  'russet potato',
  'yukon gold',
  'red potato',
  'baby potato',
  'bell pepper',
  'jalapeño',
  'jalapeno',
  'poblano pepper',
  'serrano pepper',
  'habanero',
  'shishito',
  'banana pepper',
  'cherry tomato',
  'grape tomato',
  'roma tomato',
  'beefsteak tomato',
  'heirloom tomato',
  'green onion',
  'spring onion',
  'scallion',
  'red onion',
  'white onion',
  'yellow onion',
  'vidalia onion',
  'pearl onion',
  'shallot',
  'leek',
  'garlic clove',
  'garlic bulb',
  'fresh garlic',
  'ginger root',
  'fresh ginger',
  'baby carrot',
  'rainbow carrot',
  'celery stalk',
  'celery heart',
  'iceberg lettuce',
  'romaine lettuce',
  'butter lettuce',
  'red leaf lettuce',
  'green leaf lettuce',
  'spring mix',
  'mixed greens',
  'baby spinach',
  'baby kale',
  'microgreens',
  'microgreen',
  'alfalfa sprout',
  'bean sprout',
  'broccoli rabe',
  'broccolini',
  'bok choy',
  'baby bok choy',
  'napa cabbage',
  'red cabbage',
  'green cabbage',
  'savoy cabbage',
  'brussels sprout',
  'brussels sprouts',
  'green bean',
  'green beans',
  'snap pea',
  'snow pea',
  'sugar snap',
  'english pea',
  'garden pea',
  'zucchini',
  'yellow squash',
  'butternut squash',
  'acorn squash',
  'spaghetti squash',
  'delicata squash',
  'kabocha',
  'pumpkin',
  'eggplant',
  'japanese eggplant',
  'cucumber',
  'english cucumber',
  'persian cucumber',
  'pickle cucumber',
  'asparagus',
  'artichoke',
  'artichoke heart',
  'cauliflower',
  'broccoli',
  'romanesco',
  'kohlrabi',
  'celeriac',
  'parsnip',
  'turnip',
  'rutabaga',
  'beet',
  'beets',
  'radish',
  'radishes',
  'daikon',
  'jicama',
  'fennel bulb',
  'fennel',
  'corn on the cob',
  'sweet corn',
  'corn cob',
  'okra',
  'tomatillo',
  'poblano',
  'anaheim pepper',
  'cilantro',
  'fresh cilantro',
  'flat leaf parsley',
  'italian parsley',
  'curly parsley',
  'fresh parsley',
  'fresh basil',
  'thai basil',
  'fresh mint',
  'fresh dill',
  'fresh rosemary',
  'fresh thyme',
  'fresh sage',
  'fresh oregano',
  'chive',
  'chives',
  'tarragon',
  'marjoram',
  'lemongrass',
  'bay leaf',
  'watercress',
  'arugula',
  'rocket',
  'endive',
  'radicchio',
  'frisée',
  'frisee',
  'escarole',
  'chard',
  'swiss chard',
  'collard green',
  'collard greens',
  'mustard green',
  'mustard greens',
  'dandelion green',
  'tatsoi',
  'mizuna',
  'spinach',
  'kale',
  'lettuce',
  'cabbage',
  'mushroom',
  'mushrooms',
  'shiitake',
  'portobello',
  'cremini',
  'oyster mushroom',
  'enoki',
  'maitake',
  'chanterelle',
  'morel',
  'truffle',
  'apple',
  'apples',
  'granny smith',
  'honeycrisp',
  'gala apple',
  'fuji apple',
  'orange',
  'oranges',
  'navel orange',
  'blood orange',
  'cara cara',
  'mandarin',
  'clementine',
  'tangerine',
  'satsuma',
  'lemon',
  'lemons',
  'meyer lemon',
  'lime',
  'limes',
  'key lime',
  'grapefruit',
  'pomelo',
  'ugli fruit',
  'banana',
  'bananas',
  'plantain',
  'strawberry',
  'strawberries',
  'blueberry',
  'blueberries',
  'raspberry',
  'raspberries',
  'blackberry',
  'blackberries',
  'boysenberry',
  'mulberry',
  'currant',
  'gooseberry',
  'elderberry',
  'cranberry',
  'cranberries',
  'cherry',
  'cherries',
  'grape',
  'grapes',
  'watermelon',
  'cantaloupe',
  'honeydew',
  'galia melon',
  'peach',
  'peaches',
  'nectarine',
  'nectarines',
  'apricot',
  'apricots',
  'plum',
  'plums',
  'prune plum',
  'pear',
  'pears',
  'asian pear',
  'mango',
  'mangoes',
  'papaya',
  'guava',
  'passion fruit',
  'dragon fruit',
  'pitaya',
  'kiwi',
  'kiwifruit',
  'pineapple',
  'coconut',
  'young coconut',
  'fig',
  'figs',
  'persimmon',
  'pomegranate',
  'jackfruit',
  'durian',
  'lychee',
  'rambutan',
  'star fruit',
  'carambola',
  'avocado',
  'avocados',
  'tomato',
  'tomatoes',
  'carrot',
  'carrots',
  'celery',
  'potato',
  'potatoes',
  'onion',
  'onions',
  'garlic',
  'ginger',
  'pepper',
  'peppers',
  'jalapeno',
  'squash',
  'melon',
  'berry',
  'berries',
  'fruit',
  'vegetable',
  'veggie',
  'greens',
  'sprout',
  'sprouts',
  'salad',
]);

function categorizeFood(name: string): FoodKind {
  const n = name.toLowerCase();
  for (const kw of PANTRY_KEYWORDS) {
    if (matchesKeyword(n, kw)) return 'grain';
  }
  for (const kw of DAIRY_KEYWORDS) {
    if (matchesKeyword(n, kw)) return 'dairy';
  }
  for (const kw of PROTEIN_KEYWORDS) {
    if (matchesKeyword(n, kw)) return 'meatFish';
  }
  for (const kw of PRODUCE_KEYWORDS) {
    if (matchesKeyword(n, kw)) return 'produce';
  }
  return 'other';
}

function groceryCategoryFromFood(foodName: string): string {
  const kind = categorizeFood(foodName);
  const map: Record<string, string> = {
    grain: 'Pantry',
    meatFish: 'Meat & Fish',
    produce: 'Produce',
    dairy: 'Dairy',
    other: 'Other',
  };
  return map[kind] ?? 'Other';
}

export async function generateGroceryListFromPlan(db: any, planId: number): Promise<void> {
  let rows: { meal_type: string; food_name: string; brand?: string | null; serving_size?: string | null }[] =
    await db
      .getAllAsync(
        `SELECT pm.meal_type, fi.food_name, fi.brand, fi.serving_size
     FROM PlannedMeals pm
     JOIN FoodItems fi ON fi.meal_id = pm.meal_id
     WHERE pm.meal_plan_id = ?
     ORDER BY pm.meal_order, fi.food_id`,
        [planId],
      )
      .catch(() => []);
  if (rows.length === 0) {
    const fallback = (await db
      .getAllAsync(
        'SELECT meal_type, food_name FROM MealPlanItems WHERE meal_plan_id = ? ORDER BY sort_order, item_id',
        [planId],
      )
      .catch(() => [])) as { meal_type: string | null; food_name: string }[];
    rows = fallback.map((r) => ({ meal_type: r.meal_type || 'Other', food_name: r.food_name }));
  }
  const seen = new Set<string>();
  const byCategory: Record<string, string[]> = {
    Produce: [],
    'Meat & Fish': [],
    Dairy: [],
    Pantry: [],
    Other: [],
  };
  for (const r of rows) {
    const item = r.food_name + (r.serving_size ? ` — ${r.serving_size}` : '');
    if (seen.has(item)) continue;
    seen.add(item);
    const cat = groceryCategoryFromFood(r.food_name);
    if (byCategory[cat]) byCategory[cat].push(item);
    else byCategory['Other'].push(item);
  }
  const list: { category: string; item: string; checked: boolean }[] = [];
  for (const cat of ['Produce', 'Meat & Fish', 'Dairy', 'Pantry', 'Other']) {
    for (const item of byCategory[cat]) list.push({ category: cat, item, checked: false });
  }
  await db.runAsync('UPDATE MealPlans SET grocery_list = ? WHERE meal_plan_id = ?', [
    JSON.stringify(list),
    planId,
  ]);
}

/** Case-insensitive dedupe of food names; keeps first-seen casing. */
export function dedupeFoodNamesCaseInsensitive(names: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of names) {
    if (raw == null) continue;
    const t = String(raw).trim();
    if (!t) continue;
    const k = t.toLowerCase();
    if (seen.has(k)) continue;
    seen.add(k);
    out.push(t);
  }
  return out;
}

/**
 * Build prep guide text from raw food names (deduped case-insensitively),
 * using the same category buckets as per-plan prep (grain/pantry, meat & fish, produce, dairy, other).
 */
export function buildPrepGuideTextFromUniqueFoodNames(names: string[]): string {
  const uniqueFoods = dedupeFoodNamesCaseInsensitive(names);
  if (uniqueFoods.length === 0) return '';

  const byCategory: Record<string, string[]> = {
    grain: [],
    meatFish: [],
    produce: [],
    dairy: [],
    other: [],
  };
  for (const name of uniqueFoods) {
    const cat = categorizeFood(name);
    byCategory[cat].push(name);
  }
  const steps: string[][] = [];
  if (byCategory.grain.length > 0) {
    steps.push([
      'Pantry, grains & dry goods',
      `Stock and prep shelf-stable items and starches: ${byCategory.grain.join(', ')}. Portion where helpful; store per label.`,
    ]);
  }
  if (byCategory.meatFish.length > 0) {
    steps.push([
      'Cook & portion meat & fish',
      `Prep and cook: ${byCategory.meatFish.join(', ')}. Portion into containers for each meal so you can grab and go.`,
    ]);
  }
  if (byCategory.produce.length > 0) {
    steps.push([
      'Wash and chop produce',
      `Wash, dry, and chop: ${byCategory.produce.join(', ')}. Store in containers or bags. Pre-portion for snacks if needed.`,
    ]);
  }
  if (byCategory.dairy.length > 0) {
    steps.push([
      'Portion dairy',
      `Portion out ${byCategory.dairy.join(', ')} into single-serving containers or add to meal containers as needed.`,
    ]);
  }
  steps.push([
    'Portion snacks and breakfast items',
    'Portion out any grab-and-go snacks. Prep overnight oats, egg muffins, or other breakfast items so mornings are easy.',
  ]);
  steps.push([
    'Assemble and store',
    "Label containers by day or meal (e.g. Mon Lunch, Tue Dinner). Keep in the fridge; freeze any portions you won't use within 3–4 days.",
  ]);
  const lines: string[] = ['Meal prep for the week — follow these steps in order.', ''];
  steps.forEach(([title, body], i) => {
    lines.push(`${i + 1}. ${title}`);
    lines.push(`   ${body}`);
    lines.push('');
  });
  lines.push(
    'Your plan includes: ' + uniqueFoods.slice(0, 12).join(', ') + (uniqueFoods.length > 12 ? '...' : '.'),
  );
  return lines.join('\n').trim();
}

export async function generatePrepGuideFromPlan(db: any, planId: number): Promise<void> {
  let rows: { meal_type: string; food_name: string }[] = await db
    .getAllAsync(
      `SELECT pm.meal_type, fi.food_name
     FROM PlannedMeals pm
     JOIN FoodItems fi ON fi.meal_id = pm.meal_id
     WHERE pm.meal_plan_id = ?
     ORDER BY pm.meal_order, fi.food_id`,
      [planId],
    )
    .catch(() => []);
  if (rows.length === 0) {
    rows = (await db
      .getAllAsync(
        'SELECT meal_type, food_name FROM MealPlanItems WHERE meal_plan_id = ? ORDER BY sort_order, item_id',
        [planId],
      )
      .catch(() => [])) as { meal_type: string | null; food_name: string }[];
    rows = rows.map((r) => ({ meal_type: r.meal_type || 'Meal', food_name: r.food_name }));
  }
  const text = buildPrepGuideTextFromUniqueFoodNames(rows.map((r) => r.food_name));
  await db.runAsync('UPDATE MealPlans SET prep_guide = ? WHERE meal_plan_id = ?', [text || null, planId]);
}
